stages:
    - test
    
api_tests:
    stage: test
    image: 
        name: postman/newman_alpine33
        entrypoint: [""]
    script: 
        - newman --version
        - newman run backend/HikeAdvisor.postman_collection.json